swagger: '2.0'
openapi: '3.0.0'
info:
  title: 'Oral Cancer Detect API'
  description: 'Exemplo de API para gerenciar dados de saúde.'
  version: '1.0.0'
  contact: 
    name: 'Alice Francener'
    url: 'https://github.com/alicefrancener'
  license:
    name: 'MIT License'
servers:
  - url: 'http://localhost:8080'
    description: Servidor local
paths:
  /locais:
    get:
      description: Obter todos os locais de atendimento
      tags:
      - Locais de Atendimento
      produces:
      - application/json
      responses:
        '200':
          description: 'Locais de atendimento obtidos com sucesso'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalDeAtendimento'
        '500':
          description: Locais de atendimento não puderem ser listados. Erro no servidor.
    post:
      description: Criar local de atendimento
      tags:
      - Locais de Atendimento
      consumes:
      - application/json
      requestBody:
        description: Dados do local de atendimento
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalDeAtendimento'
      responses:
        '201':
          description: Local de atendimento criado
        '400':
          description: Parâmetros ausentes ou incorretamente informados.
        '500':
          description: Local de atendimento não pode ser criado. Erro no servidor.
    put:
      description: Atualizar local de atendimento existente
      tags:
      - Locais de Atendimento
      consumes:
      - application/json
      requestBody:
        description: Dados do local de atendimento que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalDeAtendimento'
      responses:
        '201':
          description: Local de atendimento criado
        '400':
          description: Parâmetros do local de atendimento ausentes ou incorretamente informados
        '404':
          description: Local de atendimento não encontrado  
        '500':
          description: Local de atendimento não pode ser atualizado. Erro no servidor
  /locais/{regiao}:
    get:
      description: Obter todo os locais de atendimento de uma determinada região. Caso não existam locais de atendimento em uma determinada região, será retornado um array vazio.
      tags:
      - Locais de Atendimento
      produces:
      - application/json
      parameters:
      - name: regiao
        in: path
        required: true
        type: string
        description: Região de um local de atendimento.
      responses:
        '200':
          description: 'Locais de atendimento da região obtidos com sucesso'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalDeAtendimento'
        '404':
          description: Locais de atendimento não encontrados para a região fornecida
        '500':
          description: Locais de atendimento dessa região não puderem ser listados. Erro no servidor.
  /fatores:
    get:
      description: Obter todos os fatores de risco
      tags:
      - Fatores de Risco
      produces:
      - application/json
      responses:
        '200':
          description: 'Lista de fatores de risco'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FatorDeRisco'
        '500':
          description: Fatores de risco não puderem ser listados. Erro no servidor.
    post:
      description: Criar fator de risco
      tags:
      - Fatores de Risco
      consumes:
      - application/json
      requestBody:
        description: Dados do fator de risco
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FatorDeRisco'
      responses:
        '201':
          description: Fator de risco criado
        '400':
          description: Parâmetros ausentes ou incorretamente informados.
        '500':
          description: Fator de risco não pode ser criado. Erro no servidor.
    put:
      description: Atualizar fator de risco existente
      tags:
      - Fatores de Risco
      consumes:
      - application/json
      requestBody:
        description: Dados do fator de risco que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FatorDeRisco'
      responses:
        '201':
          description: Fator de risco atualizado
        '400':
          description: Parâmetros do fator de risco ausentes ou incorretamente informados
        '404':
          description: Fator de risco não encontrado  
        '500':
          description: Fator de risco não pode ser atualizado. Erro no servidor
  /lesoes:
    get:
      description: Obter lesões
      tags:
      - Lesões
      produces:
      - application/json
      responses:
        '200':
          description: 'Lista de lesões'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesao'
        '500':
          description: Fatores de risco não puderem ser listados. Erro no servidor.
    post:
      description: Criar lesao
      tags:
      - Lesões
      consumes:
      - application/json
      requestBody:
        description: Dados da lesão
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesao'
      responses:
        '201':
          description: Lesão criada
        '400':
          description: Parâmetros ausentes ou incorretamente informados.
        '500':
          description: Lesão não pode ser criada. Erro no servidor.
    put:
      description: Atualizar registro de lesão existente
      tags:
      - Lesões
      consumes:
      - application/json
      requestBody:
        description: Dados da lesão que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesao'
      responses:
        '201':
          description: Lesão atualizada
        '400':
          description: Parâmetros da lesão ausentes ou incorretamente informados
        '404':
          description: Lesão não encontrado  
        '500':
          description: Lesão não pode ser atualizada. Erro no servidor
  /rastreamentos:
    get:
      description: Obter Rastreamentos
      tags:
      - Rastreamentos
      produces:
      - application/json
      responses:
        '200':
          description: 'Lista de rastreamentos'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rastreamento'
        '500':
          description: Fatores de risco não puderem ser listados. Erro no servidor.
    post:
      description: Criar rastreamento
      tags:
      - Rastreamentos
      consumes:
      - application/json
      requestBody:
        description: Dados do rastreamento a ser criado
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rastreamento'
      responses:
        '201':
          description: Rastreamento criado
        '400':
          description: Parâmetros ausentes ou incorretamente informados.
        '500':
          description: Rastreamento não pode ser criado. Erro no servidor.
    put:
      description: Atualizar registro de rastreamento
      tags:
      - Rastreamentos
      consumes:
      - application/json
      requestBody:
        description: Dados do rastreamento que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rastreamento'
      responses:
        '201':
          description: Rastreamento atualizado
        '400':
          description: Parâmetros do rastreamento ausentes ou incorretamente informados
        '404':
          description: Rastreamento não encontrado  
        '500':
          description: Rastreamento não pode ser atualizado. Erro no servidor
  /rastreamentos/{id}:
    get:
      description: Obter rastreamento por id
      tags:
      - Rastreamentos
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: Id do rastreamento desejado
      responses:
        '200':
          description: 'Rastreamento obtido com sucesso'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rastreamento'
        '404':
          description: Rastreamento não encontrado  
        '500':
          description: Rastreamento não pode ser obtido. Erro no servidor.
  /pacientes:
    post:
      description: Criar paciente
      tags:
      - Pacientes
      consumes:
      - application/json
      requestBody:
        description: Dados do paciente a ser criado
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paciente'
      responses:
        '201':
          description: Paciente criado
        '400':
          description: Parêmetros do paciente ausentes ou incorretamente informados.
        '500':
          description: Paciente não pode ser criado. Erro no servidor.
    put:
      description: Atualizar paciente
      tags:
      - Pacientes
      consumes:
      - application/json
      requestBody:
        description: Dados do paciente que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paciente'
      responses:
        '201':
          description: Paciente atualizado
        '400':
          description: Parâmetros do paciente ausentes ou incorretamente informados
        '404':
          description: Paciente não encontrado  
        '500':
          description: Paciente não pode ser atualizado. Erro no servidor
  /pacientes/{id}:
    get:
      description: Obter paciente por id
      tags:
      - Pacientes
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: Id do paciente desejado
      responses:
        '200':
          description: 'Paciente obtido com sucesso'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paciente'
        '404':
          description: Paciente não encontrado  
        '500':
          description: Paciente não pode ser obtido. Erro no servidor.
components:
  schemas:
    Usuario:
      title: Usuário
      description: Usuário
      type: object
      properties:
        id: string
        status: string
        cpf: string
        nome: string
        password: string
        cargo: string
        regiao: string
        email: string
    LocalDeAtendimento:
      title: Local de Atendimento
      description: Local de Atendimento
      type: object
      properties:
        id:
          type: string
        nome:
          description: Nome do Local de Atendimento
          type: string
        tipo:
          description: Tipo do Local de Atendimento
          type: string
        regiao:
          description: Região do Local de Atendimento
          type: string
        bairro:
          description: Bairro do Local de Atendimento
          type: string
        cidade:
          description: Cidade do Local de Atendimento
          type: string
    FatorDeRisco:
      title: Fator de Risco
      description: Fator de Risco
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
    Lesao:
      title: Lesao
      description: Lesao
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
    Paciente:
      title: Paciente
      description: Paciente
      type: object
      properties:
        id:
          type: string
        nomePaciente:
          type: string
        regiao:
          type: string
        ultimaData:
          type: string
        ultimoProcedimento:
          type: string
        status:
          type: string
    Rastreamento:
      title: Rastreamento
      description: Rastreamento
      type: object
      properties:
        id:
          type: string
        dataAtendimento:
          type: string
        dataSugeridaRetorno:
          type: string
        paciente:
          $ref: '#/components/schemas/Paciente'
        localAtendimento:
          $ref: '#/components/schemas/LocalDeAtendimento'
        fatoresDeRisco;:
          type: array
          items:
            $ref: '#/components/schemas/FatorDeRisco'
        lesoes:
          type: array
          items:
            $ref: '#/components/schemas/Lesao'
tags:
  - name: Locais de Atendimento
    description: 'Coleção de Locais de Atendimento'
  - name: Fatores de Risco
    description: 'Coleção de Fatores de Risco'
  - name: Lesões
    description: 'Coleção de Lesões'
  - name: Rastreamentos
    description: 'Coleção de Rastreamentos'
  - name: Pacientes
    description: 'Coleção de Pacientes'
schemes:
 - https