swagger: '2.0'
openapi: 3.0.0
info:
  title: 'Oral Cancer Detect API'
  description: 'Exemplo de API para gerenciar dados de saúde.'
  version: '1.0.0'
  contact: 
    name: 'Alice Francener'
    url: 'https://github.com/alicefrancener'
  license:
    name: 'MIT License'
servers:
  - url: 'http://localhost:8080'
    description: Servidor local
paths:
  /locais:
    get:
      description: Obter todos os locais de atendimento
      tags:
      - Locais de Atendimento
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: 'Um array com todos os locais de atendimento'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalDeAtendimento'
        '500':
          description: Local de atendimento não pode ser criado. Erro no servidor.
    post:
      description: Criar local de atendimento
      tags:
      - Locais de Atendimento
      produces:
      - application/json
      requestBody:
        description: Dados do local de atendimento
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalDeAtendimento'
      responses:
        '201':
          description: Local de atendimento criado
        '400':
          description: Parâmetros ausentes ou incorretamente informados.
        '500':
          description: Local de atendimento não pode ser criado. Erro no servidor.
    put:
      description: Atualizar local de atendimento existente
      tags:
      - Locais de Atendimento
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        description: Dados do local de atendimento que se deseja atualizar 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalDeAtendimento'
      responses:
        '201':
          description: Local de atendimento criado
        '400':
          description: Parâmetros ausentes ou incorretamente informados
        '404':
          description: Local de atendimento não encontrado  
        '500':
          description: Local de atendimento não pode ser criado. Erro no servidor
  /locais/{regiao}:
    get:
      description: Obter todo os locais de atendimento de uma determinada região. Caso não existam locais de atendimento em uma determinada região, será retornado um array vazio.
      tags:
      - Locais de Atendimento
      operationId: findLocaisByRegiao
      produces:
      - application/json
      parameters:
      - name: regiao
        in: path
        required: true
        type: string
        description: Região de um local de atendimento.
      responses:
        200:
          description: 'Um array com todos os locais de atendimento da região requisitada'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalDeAtendimento'
        401:
          description: Unexpected error in API call. See HTTP response body for details.
          examples:
            application/json:
              message: Não autorizado
        404:
          description: Unexpected error in API call. See HTTP response body for details.
          examples:
            application/json:
              message: O servidor não encontrou locais para a região especificada.
  /fatores:
    get:
      summary: Obter todos os fatores de risco
      tags:
      - Fatores de Risco
      operationId: getAll
      produces:
      - application/json
      responses:
        200:
          description: 'Lista de fatores de risco'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FatorDeRisco'
        401:
          description: Unexpected error in API call. See HTTP response body for details.
          examples:
            application/json:
              message: Não autorizado
  /lesoes:
    get:
      description: ''
      summary: Obter Lesões
      tags:
      - Lesões
      operationId: getAll
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: 'Lista de lesões'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesao'
        401:
          description: Unexpected error in API call. See HTTP response body for details.
          examples:
            application/json:
              message: Não autorizado
  /rastreamentos:
    get:
      description: ''
      summary: Criar Rastreamento
      tags:
      - Rastreamento
      operationId: getAll
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: 'Lista de rastreamentos'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rastreamento'
components:
  schemas:
    Usuario:
      title: Usuário
      description: Usuário
      type: object
      properties:
        id: string
        status: string
        cpf: string
        nome: string
        password: string
        cargo: string
        regiao: string
        email: string
    LocalDeAtendimento:
      title: Local de Atendimento
      description: Local de Atendimento
      type: object
      properties:
        id:
          type: string
        nome:
          description: Nome do Local de Atendimento
          type: string
        tipo:
          description: Tipo do Local de Atendimento
          type: string
        regiao:
          description: Região do Local de Atendimento
          type: string
        bairro:
          description: Bairro do Local de Atendimento
          type: string
        cidade:
          description: Cidade do Local de Atendimento
          type: string
    FatorDeRisco:
      title: Fator de Risco
      description: Fator de Risco
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
    Lesao:
      title: Lesao
      description: Lesao
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
    Paciente:
      title: Paciente
      description: Paciente
      type: object
      properties:
        id:
          type: string
        nomePaciente:
          type: string
        regiao:
          type: string
        ultimaData:
          type: string
        ultimoProcedimento:
          type: string
        status:
          type: string
    Rastreamento:
      title: Rastreamento
      description: Rastreamento
      type: object
      properties:
        id:
          type: string
        dataAtendimento:
          type: string
        dataSugeridaRetorno:
          type: string
        paciente:
          $ref: '#/components/schemas/Paciente'
        localAtendimento:
          $ref: '#/components/schemas/LocalDeAtendimento'
        fatoresDeRisco;:
          type: array
          items:
            $ref: '#/components/schemas/FatorDeRisco'
        lesoes:
          type: array
          items:
            $ref: '#/components/schemas/Lesao'
tags:
  - name: Locais de Atendimento
    description: 'Coleção de Locais de Atendimento'
  - name: Fatores de Risco
    description: 'Coleção de Fatores de Risco'
  - name: Lesões
    description: 'Coleção de Lesões'
  - name: Rastreamento
    description: 'Coleção de Rastreamento'
schemes:
 - https